security:
  oauth2:
    client:
      clientId: comm-service
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth-service/oauth/token
      user-authorization-uri: http://localhost:8081/auth-service/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8081/auth-service/oauth/token_key

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    comm-service:
      jdbc-url: jdbc:mysql://localhost:3306/comm?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: dpc
      password: dpc123

server:
  port: 8083
  servlet:
    context-path: /comm-service

ribbon:
  connect-timeout: 1
  read-timeout: 600000


management:
  endpoints:
    web:
      exposure:
       include: "*"